/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace auth {
  export interface VerifyTokenRequest {
    token?: string;
  }
  export interface VerifyTokenResponse {
    valid?: boolean;
    userId?: string;
  }
  export interface AuthService {
    verifyToken(
      data: VerifyTokenRequest,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<VerifyTokenResponse>;
  }
}
