/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace meeting {
  export interface LeaveRoomRequest {
    roomId?: string;
    participantId?: string;
  }
  export interface LeaveRoomResponse {
    succeed?: boolean;
  }
  export interface MeetingService {
    leaveRoom(
      data: LeaveRoomRequest,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<LeaveRoomResponse>;
  }
}
